name: ytel
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  animated_custom_dropdown: ^1.2.2
  audioplayers: ^1.1.1
  cloud_firestore: ^4.2.0
  connectivity_plus: ^3.0.0
  country_picker: ^2.0.18
  csv: ^5.0.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  firebase_core: ^2.4.0
  firebase_storage: ^11.0.8
  flutter:
    sdk: flutter
  flutter_credit_card: ^3.0.4
  flutter_easyloading: ^3.0.5
  font_awesome_flutter: ^10.2.1
  get: ^4.6.5
  google_fonts: ^3.0.1
  http: ^0.13.5
  jwt_decoder: ^2.0.1
  logger: ^1.1.0
  path_provider: ^2.0.11
  persistent_bottom_nav_bar: ^5.0.2
  pretty_dio_logger: ^1.1.1
  shared_preferences: ^2.0.15
  socket_io_client: ^2.0.0
  syncfusion_flutter_charts: ^20.3.52
  toggle_switch: ^2.0.1
  url_launcher: ^6.1.7
  webview_flutter: ^4.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
